openapi: 3.0.3
info:
  description: This is an API to Retrieve IKEA ISOM Order Sync API.
  version: 1.0.4
  title: iSOM Retrieve Order API
  contact:
    name: Order-Conception-Team
    email: dl.fulfillment.scrum.team.order_conception.se@ingka.com
  x-ibm-name: ikeaOrderEnquirySync
  license:
    name: INGKA GROUP INNER SOURCE LICENCE VERSION 1.0
    url: https://github.com/ingka-group-digital/fom-ocm/tree/main/api/licence.md
tags:
  - name: iSOM Retrieve Order API
    description: iSOM Retrieve Order API
servers:
  - url: https://api.ingka.cte.ikeadt.com/om/order-management/eu/retrieve-order
    description: API Gateway DEV
  - url: https://api.ingka.ikea.com/om/order-management/eu/retrieve-order
    description: API Gateway PROD
  - url: https://api.ingka.ppe.ikeadt.com/om/order-management/eu/retrieve-order
    description: API Gateway STAGE
paths:
  "/{region}/retrieve-order":
    post:
      summary: retrieve order Info for the Order
      tags:
        - Retrieve Order Service
      operationId: IKEARetrieveOrderSync
      parameters:
        - name: region
          in: path
          required: true
          schema:
            type: string

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/retrieveOrderRequest'
      responses:
        "200":
          description: Response to retrieve order
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/retrieveOrderResponse'
        "400":
          description: Failed processing
          content:
            application/problem+json:
              schema:
                $ref: '#/components/schemas/retrieveOrderErrorResponse'
components:
  schemas:
    retrieveOrderRequest:
      $ref: '#/components/schemas/retrieveOrderRequest_order'
    retrieveOrderResponse:
      type: object
      properties:
        order:
          $ref: '#/components/schemas/retrieveOrderResponse_order'
    order_orderLines:
      type: object
      required:
        - orderLine
      properties:
        orderLine:
          $ref: '#/components/schemas/order_orderLines_orderLine'
    order_orderLines_orderLine:
      type: array
      items:
        $ref: '#/components/schemas/orderLine'
    orderLine:
      type: object
      required:
        - allowedModifications
        - extn
        - inboxList
        - isPartialStatus
        - itemDetails
        - itemGroupCode
        - orderHoldTypes
        - orderStatuses
        - orderedQty
        - origOrderLineKey
        - primeLineNo
        - shipmentLines
        - status
        - workOrders
      properties:
        itemGroupCode:
          type: string
          format: 'maximum length: 20'
          example: PROD/DS/PS
          description: Specifies whether the article is a product, delivery, or provided service type.
        primeLineNo:
          type: integer
          format: 'nonNegativeInteger (total number of digits: 5)'
          example: 2
          description: The order line number. Part of an OrderLine's unique key.
        orderedQty:
          type: integer
          format: 'decimal (total number of digits: 9, fraction digits: 2)'
          example: "10.00"
          description: The quantity of the line item that is being ordered.
        origOrderLineKey:
          type: integer
          format: 'nonNegativeInteger (total number of digits: 24)'
          example: 221120202345756576
          description: The line from which this line was derived.
        status:
          type: string
          format: 'maximum length: 40'
          example: 3700.01.100
          description: Maximum order line status among all records that belong to an order.
        isPartialStatus:
          type: string
          format: 'maximum length: 1'
          example: "Y"
          description: If order line is in more than one status then this flag will be returned as Y."
          enum:
            - "Y"
            - "N"
        plannedDeliveryDate:
          type: string
          format: date
          example: 020-08-11
          description: Range of days delivery planned date
        startTime:
          type: string
          format: time
          example: 08:00:00
          description: Range of days delivery planned date start time
        endTime:
          type: string
          format: time
          example: 18:00:00
          description: Range of days delivery planned date end time
        extn:
          $ref: '#/components/schemas/order_orderLines_orderLine_extn'
        itemDetails:
          $ref: '#/components/schemas/order_orderLines_orderLine_itemDetails'
        workOrders:
          $ref: '#/components/schemas/order_orderLines_orderLine_workOrders'
        allowedModifications:
          $ref: '#/components/schemas/order_orderLines_orderLine_allowedModifications'
        orderStatuses:
          $ref: '#/components/schemas/order_orderLines_orderLine_orderStatuses'
        orderHoldTypes:
          $ref: '#/components/schemas/order_orderLines_orderLine_orderHoldTypes'
        shipmentLines:
          $ref: '#/components/schemas/order_orderLines_orderLine_shipmentLines'
        inboxList:
          $ref: '#/components/schemas/order_orderLines_orderLine_inboxList'
      description: Contains orderline information.
    order_orderLines_orderLine_extn:
      type: object
      required:
        - hasCustomWorktopDrawing
      properties:
        hasCustomWorktopDrawing:
          type: string
          format: 'maximum length: 1'
          example: "Y"
          description: If order line item has a custom worktop drawing then this flag will be returned as Y.
          enum:
            - "Y"
            - "N"
      description: Contains orderLine extended information.
    order_orderLines_orderLine_itemDetails:
      type: object
      required:
        - itemID
      properties:
        itemID:
          type: string
          format: 'maximum length: 40'
          example: ART20350182/SGR40400001
          description: Unique id of the orderLine item.
      description: Contains orderLine item information.
    order_orderLines_orderLine_workOrders:
      type: object
      required:
        - workOrder
      properties:
        workOrder:
          $ref: '#/components/schemas/order_orderLines_orderLine_WOs_WO'
      description: Contains list of workOrders.
    order_orderLines_orderLine_WOs_WO:
      type: array
      items:
        $ref: '#/components/schemas/workOrder'
    workOrder:
      type: object
      required:
        - workOrderNo
      properties:
        workOrderNo:
          type: string
          format: 'maximum length: 40'
          example: "4201022"
          description: Number of the work order associated to the order line.
      description: Contains work order information associated to the order line.
    order_orderLines_orderLine_allowedModifications:
      type: object
      required:
        - modification
      properties:
        modification:
          $ref: '#/components/schemas/order_orderLines_orderLine_AMs_modification'
      description: Contains orderLine allowed modication information.
    order_orderLines_orderLine_AMs_modification:
      type: array
      items:
        $ref: '#/components/schemas/modification'
    modification:
      type: object
      required:
        - modificationType
      properties:
        modificationType:
          type: string
          format: 'maximum length: 40'
          example: CHANGE_SERVICE_PRICE.EX
          description: Type of the modification.
      description: List of modications.
    order_orderLines_orderLine_orderStatuses:
      type: object
      required:
        - orderStatus
      properties:
        orderStatus:
          $ref: '#/components/schemas/order_orderLines_orderLine_OSs_orderStatus'
      description: Contains list of statuses.
    order_orderLines_orderLine_OSs_orderStatus:
      type: array
      items:
        $ref: '#/components/schemas/orderStatus'
    orderStatus:
      type: object
      required:
        - status
        - statusQty
      properties:
        status:
          type: string
          format: 'maximum length: 15'
          example: 3700.01.100
          description: This field indicates the status of this opportunity.
        statusQty:
          type: integer
          format: 'decimal (total number of digits: 14, fraction digits: 2)'
          example: "4.00"
          description: The quantity currently in this status.
      description: Order status.
    order_orderLines_orderLine_orderHoldTypes:
      type: object
      required:
        - orderHoldType
      properties:
        orderHoldType:
          $ref: '#/components/schemas/order_orderLines_orderLine_OHTs_orderHoldType'
      description: Contains orderLine hold type information.
    order_orderLines_orderLine_OHTs_orderHoldType:
      type: array
      items:
        $ref: '#/components/schemas/orderHoldType'
    orderHoldType:
      type: object
      required:
        - holdType
        - status
      properties:
        holdType:
          type: string
          format: 'maximum length: 20'
          example: ReadyToAssignHold
          description: Type of the hold.
        status:
          type: string
          format: 'maximum length: 15'
          example: "1300"
          description: Status of the order hold type.
      description: List of all the hold types defined for an order.
    order_orderLines_orderLine_shipmentLines:
      type: object
      required:
        - shipmentLine
      properties:
        shipmentLine:
          $ref: '#/components/schemas/order_orderLines_orderLine_SLs_shipmentLine'
      description: Contains orderLine shipment information.
    order_orderLines_orderLine_SLs_shipmentLine:
      type: array
      items:
        $ref: '#/components/schemas/shipmentLine'
    shipmentLine:
      type: object
      required:
        - quantity
        - shipment
      properties:
        quantity:
          type: integer
          format: 'decimal (total number of digits: 14, fraction digits: 2)'
          example: "4.00"
          description: The shipment line quantity.
        shipment:
          $ref: '#/components/schemas/order_OLs_OL_SLs_SL_shipment'
      description: List of shipments created for the order line.
    order_OLs_OL_SLs_SL_shipment:
      type: array
      items:
        $ref: '#/components/schemas/shipment'
    shipment:
      type: object
      required:
        - extn
      properties:
        extn:
          $ref: '#/components/schemas/order_OLs_OL_SLs_SL_shipment_extn'
      description: Information of the shipment which contains the orderline.
    order_OLs_OL_SLs_SL_shipment_extn:
      type: object
      required:
        - cduID
        - workOrderNo
      properties:
        cduID:
          type: string
          format: 'maximum length: 50'
          example: "3565656"
          description: CDU ID.
        workOrderNo:
          type: integer
          format: 'nonNegativeInteger (total number of digits: 40)'
          example: 4201022
          description: Number of the work order associated to the shipment.
      description: Extended information of the shipment.
    order_orderLines_orderLine_inboxList:
      type: object
      required:
        - inbox
      properties:
        inbox:
          $ref: '#/components/schemas/order_orderLines_orderLine_IL_inbox'
      description: Contains orderLine deviation information.
    order_orderLines_orderLine_IL_inbox:
      type: array
      items:
        $ref: '#/components/schemas/inbox'
    inbox:
      type: object
      required:
        - inboxKey
        - inboxReferencesList
        - queueId
      properties:
        inboxKey:
          type: integer
          format: 'nonNegativeInteger (total number of digits: 24)'
          example: "202011221909181622601198"
          description: Unique identifier of order line deviation.
        queueId:
          type: string
          format: 'maximum length: 40'
          example: IKEA_DELAYED_ORDER_ITEM
          description: Name of the queue where the deviation was published.
        inboxReferencesList:
          $ref: '#/components/schemas/order_orderLines_orderLine_IL_inbox_IRL'
      description: Deviation information of the order line.
    order_orderLines_orderLine_IL_inbox_IRL:
      type: object
      required:
        - inboxReferences
      properties:
        inboxReferences:
          $ref: '#/components/schemas/order_orderLines_orderLine_IL_inbox_IRL_IRs'
      description: List of inbox refernces.
    order_orderLines_orderLine_IL_inbox_IRL_IRs:
      type: array
      items:
        $ref: '#/components/schemas/inboxReferences'
    inboxReferences:
      type: object
      required:
        - name
        - value
      properties:
        name:
          type: string
          format: 'maximum length: 40'
          example: ITEMID
          description: Name of the inbox reference.
        value:
          type: string
          format: 'maximum length: 2000'
          example: ART20458559
          description: Value of the inbox reference.
      description: InboxReferences.
    order_orderLineRelationships:
      type: object
      required:
        - orderLineRelationship
      properties:
        orderLineRelationship:
          $ref: '#/components/schemas/order_orderLineRelationships_orderLineRelationship'
      description: The type of relationship between the parent and the child line.
    order_orderLineRelationships_orderLineRelationship:
      type: array
      items:
        $ref: '#/components/schemas/orderLineRelationship'
    orderLineRelationship:
      type: object
      required:
        - childLine
        - parentLine
        - relationshipType
      properties:
        relationshipType:
          type: string
          format: 'maximum length: 40'
          example: DELIVERY / SERVICE
          description: The type of relationship between order lines.
        parentLine:
          $ref: '#/components/schemas/orderLineRelationship_parentLine'
        childLine:
          $ref: '#/components/schemas/orderLineRelationship_childLine'
      description: The type of relationship between the parent and the child line.
    retrieveOrderRequest_order:
      type: object
      required:
        - countryCode
        - orderNo
        - userRole
      properties:
        countryCode:
          type: string
          format: maximum length:5
          example: GB
          description: Country Code to identify to which country the order belongs to.
        orderNo:
          type: string
          format: 'maximum length: 40'
          example: "1091774407"
          description: Number of the iSOM order.
        userRole:
          type: string
          format: 'maximum length: 40'
          example: HADV-TRUCK
          description: Selling channel logged in user role.
    retrieveOrderResponse_order:
      type: object
      required:
        - countryCode
        - orderLineRelationships
        - orderLines
        - orderNo
      properties:
        countryCode:
          type: string
          format: maximum length:5
          example: GB
          description: Country Code to identify to which country the order belongs to.
        orderNo:
          type: string
          format: 'maximum length: 40'
          example: "1091774407"
          description: Number of the iSOM order.
        orderLines:
          $ref: '#/components/schemas/order_orderLines'
        orderLineRelationships:
          $ref: '#/components/schemas/order_orderLineRelationships'
    orderLineRelationship_parentLine:
      type: object
      required:
        - primeLineNo
      properties:
        primeLineNo:
          type: integer
          format: 'nonNegativeInteger (total number of digits: 5)'
          example: 1
          description: The parent order line number.
      description: Parent orderLine.
    orderLineRelationship_childLine:
      type: object
      required:
        - primeLineNo
      properties:
        primeLineNo:
          type: integer
          format: 'nonNegativeInteger (total number of digits: 5)'
          example: 1
          description: The child order line number.
      description: Child orderLine.
    retrieveOrderErrorResponse:
      type: object
      properties:
        type:
          type: string
        error:
          $ref: '#/components/schemas/retrieveOrderErrorResponse_error'
        title:
          type: string
          description: |
            A short, summary of the problem type. Written in english and readable
            for engineers (usually not suited for non technical stakeholders and
            not localized); example: Service Unavailable
    retrieveOrderErrorResponse_error:
      type: object
      required:
        - errorCode
        - errorDescription
      properties:

        errorCode:
          type: string
          format: maximum length:40
          example: EXTN_SOMCO_0007
          description: Unique identifier of the error.
        errorDescription:
          type: string
          format: maximum length:40
          example: Invalid Order
          description: Description of the error.
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
security:
  - bearerAuth: []